server:
  port: ${PORT}

spring:
  datasource:
    url: ${POSTGRESQL_URL}
    username: ${POSTGRESQL_USERNAMEL}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa: 
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  mail:
    host: smtp.gmail.com
    port: ${SMTP_PORT}
    username: ${SMTP_USER}
    password: ${SMTP_PASS}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

jwt:
  access_time: ${JWT_ACCESS_TIME}
  refresh_time: ${JWT_REFRESH_TIME}
  secret: ${SECRET}