server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:3306/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  
  jpa: 
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: abdusharipovizzat03@gmail.com
    password: xlrv btce vuga kntq
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true


jwt:
  secret: uzbekistanrepubliccoders2025
  access_token_expiration: 900000
  refresh_token_expiration: 604800000
